<?php
/**
 * Created by O2System Framework File Generator.
 * DateTime: CREATE_DATETIME
 */

// ------------------------------------------------------------------------

namespace NAMESPACE;

// ------------------------------------------------------------------------

/**
 * Class CLASS
 *
 * @package PACKAGE
 */
class CLASS extends \O2System\Framework\Http\Controller
{
    /**
     * CLASS::__reconstruct
     */
    public function __reconstruct()
    {
        // TODO: Change the autogenerated stub
    }
}