<?php
/**
 * Created by O2System Framework File Generator.
 * DateTime: CREATE_DATETIME
 */

// ------------------------------------------------------------------------

namespace NAMESPACE;

// ------------------------------------------------------------------------

/**
 * Class CLASS
 *
 * @package PACKAGE
 */
class CLASS
{
    public function __construct()
    {
        // TODO: Change the autogenerated stub
    }
}