<?php
/**
 * Created by O2System Framework File Generator.
 * DateTime: CREATE_DATETIME
 */

// ------------------------------------------------------------------------

use BASE_MIGRATION

/**
 * Class CLASS
 */
class CLASS extends Migration
{
    /**
     * CLASS::up
     */
    public function up()
    {
        // TODO: Change the autogenerated stub
    }

    // ------------------------------------------------------------------------

    /**
     * CLASS::down
     */
    public function down()
    {
        // TODO: Change the autogenerated stub
    }

    // ------------------------------------------------------------------------

    /**
     * CLASS::seed
     */
    public function seed()
    {
        // TODO: Change the autogenerated stub
    }
}